spring:
  profiles:
    active:
      - pro
---
spring:
  profiles: pro
  application:
    name: dev
---
spring:
  profiles: dev
  application:
    name: dev
---
spring:
  profiles: test
  application:
    name: test
