spring:
  profiles:
    active: test

---
spring:
  profiles: test
  application:
    name: test
---
spring:
  profiles: pro
  application:
    name: pro
---
spring:
  profiles: dev
  application:
    name: dev