spring:
  profiles:
    active:
      - test2
---
spring:
  profiles: test1
  application:
    name: test1
---
spring:
  profiles: test2
  application:
    name: test2
---
spring:
  profiles: test3
  application:
    name: test3