spring:
    profiles:
      active: dev
---
spring:
  profiles: dev
server:
  port:  8101
  context-path: /cloud
##############################################################################
###  eureka服务注册配置   ###
##############################################################################
eureka:
  client:
    service-url:
      defaultZone: http://edmin:eurekadmin@eureka-7001.giims.org:7001/eureka,http://edmin:eurekadmin@eureka-7002.giims.org:7002/eureka,http://edmin:eurekadmin@eureka-7003.giims.org:7003/eureka # eureka服务器集群的地址
  instance:
    instance-id: company-8101.giims.org #客户端服务器的地址
    prefer-ip-address:  true #在eureka服务器中是否通过客户端的IP地址访问，否则使用计算机名称访问
    #lease-expiration-duration-in-seconds: 90 #服务器如果在默认90秒内没有检测到客户端的心跳，则清理该服务，不建议修改此项
    #lease-renewal-interval-in-seconds: 30 #客户端心跳频率，默认30秒一次，不建议修改此项
info:
  app.name: giims-microcloud
  company.name: giims.org
  build.artifactId: $project.artifactId$
  build.version: $project.version$
spring:
##############################################################################
###  eureka服务注册的服务名称   ###
##############################################################################
  application:
      name: microcloud-provider-company

##############################################################################
###  使用阿里巴巴druid配置数据库   ###
##############################################################################
# 数据库访问配置
# 主数据源，默认的
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/giims8001?useUnicode=true&amp;characterEncoding=utf-8
    username: root
    password: MS451103
# 下面为连接池的补充设置，应用到上面所有数据源中
# 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
# 配置获取连接等待超时的时间
    maxWait: 60000
# 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
# 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
# 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
# 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
# 通过connectProperties属性来打开mergeSql功能；慢SQL记录，sql执行的时间操作druid.stat.slowSqlMillis设置的时间则记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

# 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat=true
##############################################################################
###  mybatis-plus 配置   ###
##############################################################################
mybatis-plus:
  #mapper.xml文件位置，需要将自动生成或自己创建的与mapper.java对应的mapper.xml复制到resources文件夹在的mapper文件夹下
  mapper-locations: classpath:/mapper/**/*Dao.xml
  #实体扫描，实体类别名，多个package用逗号或者分号分隔
  type-aliases-package: org.giims.microcloud.*.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #数据库大写下划线转换
    #capital-mode: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #序列接口实现类配置
    #key-generator: cn.jeefast.xxx
    #逻辑删除配置
    logic-delete-value: 0
    logic-not-delete-value: 1
    #自定义填充策略接口实现
    #meta-object-handler: cn.jeefast.xxx
    #自定义SQL注入器
    #sql-injector: cn.jeefast.xxx
  configuration:
    map-underscore-to-camel-case: true
    #二级缓存
    cache-enabled: false
##############################################################################
###  日志 配置   ### 如果配置了 logback-spring.xml，此处优先级高于logback-spring.xml配置
##############################################################################
logging:
  level:
    org.giims: DEBUG
    org.springframework.web: INFO # spring框架的日志显示级别
    org.springboot.sample: INFO
---
spring:
  profiles: pro
server:
  port:  8102
  context-path: /cloud
##############################################################################
###  eureka服务注册配置   ###
##############################################################################
eureka:
  client:
    service-url:
      defaultZone: http://edmin:eurekadmin@eureka-7001.giims.org:7001/eureka,http://edmin:eurekadmin@eureka-7002.giims.org:7002/eureka,http://edmin:eurekadmin@eureka-7003.giims.org:7003/eureka # eureka服务器集群的地址
  instance:
    instance-id: company-8102.giims.org #客户端服务器的地址
    prefer-ip-address:  true #在eureka服务器中是否通过客户端的IP地址访问，否则使用计算机名称访问
    #lease-expiration-duration-in-seconds: 90 #服务器如果在默认90秒内没有检测到客户端的心跳，则清理该服务，不建议修改此项
    #lease-renewal-interval-in-seconds: 30 #客户端心跳频率，默认30秒一次，不建议修改此项
info:
  app.name: giims-microcloud
  company.name: giims.org
  build.artifactId: $project.artifactId$
  build.version: $project.version$
spring:
##############################################################################
###  eureka服务注册的服务名称   ###
##############################################################################
  application:
      name: microcloud-provider-company

##############################################################################
###  使用阿里巴巴druid配置数据库   ###
##############################################################################
# 数据库访问配置
# 主数据源，默认的
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/giims8001?useUnicode=true&amp;characterEncoding=utf-8
    username: root
    password: MS451103
# 下面为连接池的补充设置，应用到上面所有数据源中
# 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
# 配置获取连接等待超时的时间
    maxWait: 60000
# 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
# 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
# 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
# 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
# 通过connectProperties属性来打开mergeSql功能；慢SQL记录，sql执行的时间操作druid.stat.slowSqlMillis设置的时间则记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

# 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat=true
##############################################################################
###  mybatis-plus 配置   ###
##############################################################################
mybatis-plus:
  #mapper.xml文件位置，需要将自动生成或自己创建的与mapper.java对应的mapper.xml复制到resources文件夹在的mapper文件夹下
  mapper-locations: classpath:/mapper/**/*Dao.xml
  #实体扫描，实体类别名，多个package用逗号或者分号分隔
  type-aliases-package: org.giims.microcloud.*.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #数据库大写下划线转换
    #capital-mode: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #序列接口实现类配置
    #key-generator: cn.jeefast.xxx
    #逻辑删除配置
    logic-delete-value: 0
    logic-not-delete-value: 1
    #自定义填充策略接口实现
    #meta-object-handler: cn.jeefast.xxx
    #自定义SQL注入器
    #sql-injector: cn.jeefast.xxx
  configuration:
    map-underscore-to-camel-case: true
    #二级缓存
    cache-enabled: false
##############################################################################
###  日志 配置   ### 如果配置了 logback-spring.xml，此处优先级高于logback-spring.xml配置
##############################################################################
logging:
  level:
    org.giims: DEBUG
    org.springframework.web: INFO # spring框架的日志显示级别
    org.springboot.sample: INFO
