spring:
  profiles:
    active:
    - test
---
spring:
  profiles: test
  application:
    name: microcloud-test
---
spring:
  profiles: pro
  application:
    name: microcloud-pro
---
spring:
  profiles: dev
  application:
    name: microcloud-dev
