spring:
  profiles:
    active:
    - dev
  application:
    name: microcloud-provider-company
eureka:
  client:
    service-url:
      defaultZone: http://edmin:eurekadmin@eureka-7001.giims.org:7001/eureka,http://edmin:eurekadmin@eureka-7002.giims.org:7002/eureka,http://edmin:eurekadmin@eureka-7003.giims.org:7003/eureka 
---
spring:
  profiles: dev
server:
  port:  8101
---
spring:
  profiles: pro
server:
  port:  8102
